### ISSUE TITLE
Image transform is lowering the saturation

### ISSUE THREAD

**Issue by jomotion11** [madebyshape/craft-3#15]
Same image taken from lulu kitchen is uploaded to new site and appears greyer/less saturated.

**Comment by jomotion11** [comment]
Looking further into the issue. Files  being saved in assets/images are fine but the file created in web/images/dist are greyer

**Comment by bymayo** [comment]
Fixed in https://github.com/madebyshape/craft-3/commit/147b073421eca176eb7bf3539d60ec1cf3b84edf
