### ISSUE TITLE
extremely slow localhost/webpack

### ISSUE THREAD

**Issue by RamonArno** [madebyshape/craft-3#26]
Whenever i run `npm run dev` my localhost starts up but does not finish loading. Whenever i change a **.scss** file it takes over 15-20 seconds to finish. (Chaning a **.js** file is fine, takes less than 1s)

**Comment by bymayo** [comment]
@RamonArno We've found this is an issue if you have a lot of CSS to compile.

I'm in the middle of reworking this in Webpack (The version your likely using is just Gulp) and I've found the speed increased.

Are you using Tailwind? Or a lot of custom CSS using SCSS?

**Comment by RamonArno** [comment]
@bymayo Thanks for the reply, i'm having this issue with a clean install of the project. I'm indeed using Gulp, as intended with this repo i thought?

**Comment by bymayo** [comment]
@RamonArno Yeah thats right, so do you have a lot of CSS compiling?

**Comment by RamonArno** [comment]
@bymayo No, not at all. The only thing i changed was a font color to test things out, from there i noticed it took 15-20 second to finish. Else, everything is as it is out of the box when i `composer create-project ` the repo.

**Comment by RamonArno** [comment]
@bymayo Would there be any kind of update on this issue?

**Comment by bymayo** [comment]
@RamonArno I'm in the middle of releasing 3.x.x of this framework, which should fix this issue and uses Webpack.

**Comment by bymayo** [comment]
@RamonArno Released that now, if you want to give 3.0.0 a go. This now uses Webpack mixed with Gulp (For now) as we're in the middle of transitioning to full Webpack over next month. Just allows you to use some more advanced JS Webpack features.

Also includes VueJS 3 by default as well.
